apiVersion: v1
kind: Service
metadata:
  name: {{ include "test.fullname" . }}
spec:
  selector:
    app: {{ include "test.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
  type: {{ .Values.service.type }}

